import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import NavBar from "./Components/NavBar";
import { Provider } from "jotai";
import "./globals.css";

const dmSans = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Provider>
      <html lang="en">
        <body className={`${dmSans.className} flex`}>
          <NavBar />
          {children}
        </body>
      </html>
    </Provider>
  );
}
